#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'getTotalGoals' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING team
#  2. INTEGER year
#

import requests

def getTotalGoals(team, year):
    goals = 0
    page = 1
    while True:
        url = "https://jsonmock.hackerrank.com/api/football_matches?year={}&team1={}&page={}".format(year, team, page)
        response = requests.get(url).json()
        if not response['data']:  # Break if no more data on current page
            break
        for match in response['data']:
            goals += int(match['team1goals'])
        page += 1
    
    page = 1
    while True:
        url = "https://jsonmock.hackerrank.com/api/football_matches?year={}&team2={}&page={}".format(year, team, page)
        response = requests.get(url).json()
        if not response['data']:  # Break if no more data on current page
            break
        for match in response['data']:
            goals += int(match['team2goals'])
        page += 1
    
    return goals

# Example usage:
team = 'Barcelona'
year = 2011
total_goals = getTotalGoals(team, year)
print(total_goals)
if _name_ == '_main_':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    team = input()

    year = int(input().strip())

    result = getTotalGoals(team, year)

    fptr.write(str(result) + '\n')

    fptr.close()
